name: Deploy to EC2
on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  Install:
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
      - name: Setup NodeJS
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 10
      - name: Cache node modules
        uses: actions/cache@v3.0.11
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('**/package-lock.json') }}
          restore-keyes: node_modules-
      - name: Install packages with npm
        run: |
          npm ci

  Build:
    needs: Install
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
      - name: Setup NodeJS
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 10
      - name: Cache node modules
        uses: actions/cache@v3.0.11
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('**/package-lock.json') }}
      - name: Build
        run: |
          npm rebuild node-sass --force
          npm run build -- --colors
      - name: Cache Node modules and build folder
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: actions/cache@v3.0.11
        with:
          path: |
            ~/.npm
            ./node_modules
            ./build
          key: ${{ runner.os }}-build-${{ github.run_id }}
          restore-keyes: ${{ runner.os }}-build-${{ github.run_id }}

  Test:
    needs: Install
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
      - name: Setup NodeJS
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 10
      - name: Cache node modules
        uses: actions/cache@v3.0.11
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('**/package-lock.json') }}
      - name: Run tests
        run: |
          npm run test -- --colors

  Deploy:
    needs:
      - Build
      - Test
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
      #- name: Run Ansible playbook
        #uses: dawidd6/action-ansible-playbook@v2.6.1
        #with:
          #playbook: ec2_deploy.yml
          #key: ${{ secrets.SSH_PRIV_KEY }}
          #vault_password: ${{ secrets.VAULT_PASSWORD }}
      